### ISSUE TITLE
 我测试还是有几次 pop 有问题的

### ISSUE THREAD

**Issue by manajay** [asd8855/Can-t-add-self-as-subview#1]
A-B-C 应该是 从 C pop B 再 pop 到  A 连续的时候回出问题

**Comment by asd8855** [comment]
我们是出现在push的时候，pop的时候具体还没试。你这个是不是pop的时候页面卡顿了

**Comment by manajay** [comment]
@asd8855 不是卡住, 是因为连续pop 的时候, 在 B pop 的过程动画中, 再次 pop A (当然理论上 B 已经被 pop 出去了, 只是动画没有结束应该是), 那么就会导致, A的pop失败. 
当然这个和你 hook 预防同时 pop 还是不太一样的. 
我举的例子其实还不算太严重, 自己在写代码的时候调试一下 , 预防这个情况就好了

**Comment by manajay** [comment]
新项目引入没有问题, 老项目就要一个一个检查 类似的连续 push 问题有没有影响
